// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu0MxnkrtZUMZ0t7eLNsnvFjCBuvihyTg',
    appId: '1:902703168376:web:161d4bdc749f7995b3e68d',
    messagingSenderId: '902703168376',
    projectId: 'otptest-368da',
    authDomain: 'otptest-368da.firebaseapp.com',
    storageBucket: 'otptest-368da.appspot.com',
    measurementId: 'G-X58NHL5VZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRmxvCc6W7V80dnq02hlQ8pA1aCuG3oWU',
    appId: '1:902703168376:android:2bff35b85b4cc70ab3e68d',
    messagingSenderId: '902703168376',
    projectId: 'otptest-368da',
    storageBucket: 'otptest-368da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7scn5Fxu1_iAYbih13fAa4mGgR9i7mRk',
    appId: '1:902703168376:ios:8cdd9fd302a64eb4b3e68d',
    messagingSenderId: '902703168376',
    projectId: 'otptest-368da',
    storageBucket: 'otptest-368da.appspot.com',
    iosBundleId: 'com.example.otptestdelete',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7scn5Fxu1_iAYbih13fAa4mGgR9i7mRk',
    appId: '1:902703168376:ios:6cb874e398234e25b3e68d',
    messagingSenderId: '902703168376',
    projectId: 'otptest-368da',
    storageBucket: 'otptest-368da.appspot.com',
    iosBundleId: 'com.example.otptestdelete.RunnerTests',
  );
}
